---
k3s_cluster:
  children:
    master:
      hosts:
        mobius-controller-1:
          ansible_host: 192.168.86.88
    node:
      hosts:
        mobius-worker-1:
          ansible_host: 192.168.86.89
        mobius-worker-2:
          ansible_host: 192.168.86.90
        mobius-worker-3:
          ansible_host: 192.168.86.91
  vars:
    k3s_version: v1.22.3+k3s1
    ansible_user: ansible
    systemd_dir: /etc/systemd/system
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""