---

k3s_cluster:
  children:
    master:
      hosts:
        mobius-controller-1.local:
    node:
      hosts:
        mobius-worker-[1:3].local:
  vars:
    k3s_version: v1.22.3+k3s1
    ansible_user: ansible
    systemd_dir: /etc/systemd/system
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""