---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes

  tasks:
    - name: Ensure libnss-mdns is latest.
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
        name: libnss-mdns
        state: latest

    - name: Ensure iperf3 is latest.
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
        name: iperf3
        state: latest