---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes

  tasks:
    - name: Ensure all packages are latest.
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
        upgrade: dist