---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: grafana-ingress
  namespace: default

spec:
  rules:
    - host: grafana.mobius
      http:
        paths:
          - path: /
            backend:
              serviceName: my-release-grafana
              servicePort: 80