---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes

  tasks:
    - name: Ensure open-iscsi is installed.
      apt:
        name: open-iscsi
        state: latest
    
    - name: Ensure iscsid is running and starts at boot.
      systemd:
        name: iscsid
        state: started
        enabled: yes
        daemon_reload: yes